{{- if .Values.publishTemplates.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: publish-templates-ig
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac.labels" . | nindent 4 }}
data:
  OSAC_TEMPLATE_COLLECTIONS: {{ .Values.publishTemplates.templateCollections | quote }}
  OSAC_FULFILLMENT_SERVICE_URI: {{ .Values.publishTemplates.fulfillmentServiceUri | quote }}
{{- end }}
